### ISSUE TITLE
Can you help me brother?

### ISSUE THREAD

**Issue by Pratikshresth** [yoelbassin/DHCP-starvation#1]
Hello brother I was trying out your code with the cisco 3725 router. It successfully starvet the DHCP server but after the attack it gets released very quickly. What might be the problem? In the arp table of cicso router, the generated mac address is shown ad INCOMPLETE. Can you help out with this? Soo Sorry for the previous issue.
![Capture1](https://user-images.githubusercontent.com/58677787/121307157-70e29a00-c91f-11eb-8e59-81151ccd7a65.PNG)
![Capture](https://user-images.githubusercontent.com/58677787/121307161-7213c700-c91f-11eb-9223-a0c89581091b.PNG)

**Comment by yoelbassin** [comment]
Could you add a Wireshark snapshot of the procedure? (The DHCP d-o-r-a and any arp req/resp that may be related)

**Comment by Pratikshresth** [comment]
In wireshark the router is generating a broadcast Who has IP address?
![Capture3](https://user-images.githubusercontent.com/58677787/121309403-db94d500-c921-11eb-903e-f04bb4208da8.PNG)
![Capture4](https://user-images.githubusercontent.com/58677787/121309459-eea7a500-c921-11eb-8f94-573ca36f975f.PNG)

**Comment by yoelbassin** [comment]
Could you filter it by dhcp || arp so it could show a better correlation between the two?

**Comment by Pratikshresth** [comment]
There you go
![Capture5](https://user-images.githubusercontent.com/58677787/121310750-6a562180-c923-11eb-8972-16b9091f7967.PNG)

**Comment by yoelbassin** [comment]
Could you upload the .pcap file from wireshark? It would make the analysis much easier for me
If you can't upload it here, please send it to bassin.yoel@gmail.com

**Comment by Pratikshresth** [comment]
[dhcp.zip](https://github.com/yoelbassin/DHCP-starvation/files/6621877/dhcp.zip)

**Comment by yoelbassin** [comment]
could you try running the new code? now it will send arp replies to the DHCP server to save its mac in the its arp table

**Comment by Pratikshresth** [comment]
Sure, I will try. Thank you so much brother, Actually i am coding for the full bundled tool for my University project and i am taking reference from all over the internet resources. Thank you soo much. I will try the updated code.
